backend:
  name: git-gateway
  branch: main 

local_backend: true

// publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
show_preview_links: false

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Date", name: "date", widget: "date" }
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: "image", name: "image", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }
  